import { CSpinner } from "@coreui/react";
import { Suspense } from "react";
import DefaultLayout from "./DefaultLayout";
import ReduxProvider from "./ReduxProvider";

import "./scss/style.scss";

export const metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({ children }) {
   return (
      <html lang="id">
         <body>
            <ReduxProvider>
               <Suspense
                  fallback={
                     <div className="pt-3 text-center">
                        <CSpinner color="primary" variant="grow" />
                     </div>
                  }>
                  <DefaultLayout>{children}</DefaultLayout>
               </Suspense>
            </ReduxProvider>
         </body>
      </html>
   );
}
